### PR TITLE
Adding Sign Language Classifier to the application model zoo

### PR DESCRIPTION
**Pull request by Aanisha**
Adding Sign Language Classifier notebook, to the application model zoo.

### CODE REVIEW

**Comment by THEFASHIONGEEK** [comment]
Hi Aanisha,

Can you please add a demo tutorial at the start of the notebook. You can see this [notebook](https://github.com/Tessellate-Imaging/monk_v1/blob/master/study_roadmaps/4_image_classification_zoo/Classifier%20-%20Zalando%20Clothing%20Store.ipynb).

**Comment by abhi-kumar** [comment]
Thank you for adding the tutorial. The format is
a) Installation
b) Running a pretrained classifier on test sets
c) Training
d) Validation (if any)
e) Inference on test sets (optional)

As mentioned by @THEFASHIONGEEK please format your notebook in that manner so that all tutorials have the same structure. Push the "Running a pretrained classifier" to the second section followed by the training section.

**Comment by Aanisha** [comment]
I have made the changes as suggested.

**Comment by abhi-kumar** [comment]
Thank you for the tutorial. In the next tutorials please remove the absolute colab paths, so that the tutorial can be used elsewhere too. For this one the team will make the necessary changes in the code

**Pull request merged**
