### PR TITLE
Dependency Issue Solved

### PR DESCRIPTION
**Pull request by pranavmicro7**

### CODE REVIEW

**Comment by abhi-kumar** [comment]
Post the update of tensorflow 1.12 to 1.15.2 please run the run_tests.py file in system_check_tests and system_unit_tests and check if system passes all tests?

**Comment by pranavmicro7** [comment]
Before the update of TensorFlow 1.12 I'm getting following error while installing packages from requirements_cpu.txt

`ERROR: Could not find a version that satisfies the requirement tensorflow==1.12.0 (from -r requirements_cpu.txt (line 14)) (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 1.15.2, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.1.0rc0, 2.1.0rc1, 2.1.0rc2, 2.1.0)
ERROR: No matching distribution found for tensorflow==1.12.0 (from -r requirements_cpu.txt (line 14))`

The error gets resolved by updating Tensoflow 1.12 to 1.15.2. The test_logs of system_unit_tests and system_check_tests acquired are -
[test_logs.txt](https://github.com/Tessellate-Imaging/monk_v1/files/4217300/test_logs.txt)
[test_logs.txt](https://github.com/Tessellate-Imaging/monk_v1/files/4217302/test_logs.txt)

While running the run_test.py I'm getting the following warning:
` I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA`

**Comment by abhi-kumar** [comment]
Instead of version 1.15 try 1.13.1, and run the tests. Once it passes all the tests with 1.13.1 will merge the pull

**Comment by abhi-kumar** [comment]
CPU requirements added. Closing the commit without merging.

**Pull request closed without merging**
